### PR TITLE
Fix import for aggregated models

### LINKED ISSUE #337: Problem with aggregators in 4.1.0 version
- Symfony version: 4.4.4
- Algolia Search Bundle version: 4.1.0
- Algolia Client Version: 2.5.1

### Description
Aftere upgrade to 4.1.0 indexing aggregators is broken. After revert to 4.0.0 everything is working fine. 
It looks like that this part of code in SearchImportCommand is to blame:
https://github.com/algolia/search-bundle/blob/6714243a8eb87153b68a4efdb94c7d7349f60eda/src/Command/SearchImportCommand.php#L90-L92
Because $entityClassName is changed before from Agreggator class to Entity class and isSearchable is looking in array where is only Aggregator.
Without this condition this method is also failing on this line:
https://github.com/algolia/search-bundle/blob/6714243a8eb87153b68a4efdb94c7d7349f60eda/src/Command/SearchImportCommand.php#L96
Because of the same reason: indice is assigned to Aggregator class not entity.

### Steps To Reproduce
1) create aggregator with multiple entities
2) run search:import
3) nothing happens. There are no messages: "Indexed A/B CLASS entities into INDEX". But there is message "Done!". Nothing changes in index.

### PR DESCRIPTION
**Pull request by ottaviano**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no    
| BC breaks?        | no     
| Related Issue     | Fix #337
| Need Doc update   | no

## Describe your change

This PR fix the import command which actually skips aggregated entities (Aggregator model).

### CODE REVIEW

**Comment by chloelbn** [comment]
Hey @ottaviano !

Thanks a lot for your contribution. Would you mind adding some tests to your PR please?

**Comment by ottaviano** [comment]
Hi @chloelbn, sure, but it seems that the tests depend on real Algolia backend? How can I run the test on local without real `ALGOLIA_APP_ID` and `ALGOLIA_API_KEY`?

**Comment by ottaviano** [comment]
@chloelbn, is there a way to run the tests on local without a real Algolia API keys?

**Comment by chloelbn** [comment]
Hi @ottaviano, you can chose to run only the tests you created and not the whole test suite, so it won't eat up your units in your account. It's not ideal but shouldn't be an extreme rise in your operations. If you don't have an Algolia account, you can create a free one with a small dataset [here](https://www.algolia.com/pricing/). Don't hesitate to ping me again if it's not clear!

**Comment by wlasnapl** [comment]
Do you know when this will be merged and released?

**Comment by keichinger** [comment]
@chloelbn we're running into the same issue/bug. How can we help getting this PR merged and released?

**Comment by chloelbn** [comment]
Hi @keichinger, thanks for your offer to help! You can write tests to make this move forward :)

**Comment by ottaviano** [comment]
Hi @keichinger, sorry for the wait :(

@chloelbn, I saw that there is already a test for the command `search:index` and I improve it to really test the case of aggregation.
Could you review, please?

**Comment by keichinger** [comment]
@ottaviano no worries! Anyone could have helped you out of there :) Especially during the holidays.

I'm glad that you've found the time to finish up this PR ☺️ I was planning on having a closer look at this PR tomorrow in the morning :) Guess that's no longer needed.

**Review by chloelbn — APPROVED** [review]

**Pull request merged**
