### PR TITLE
Add a DataCollector with debug toolbar integration

### PR DESCRIPTION
**Pull request by venyii**
This PR adds a DataCollector that records all transactions within a Symfony application.

In debug mode, the `\AlgoliaSearch\Client` will be replaced by `Algolia\AlgoliaSearchBundle\Debug\DebugClient`. With this, it's possible to:

- Fetch transactions in your functional tests:
```
// Test extending WebTestCase
$client = static::createClient();
$client->enableProfiler();
// Do something, e.g. controller request
$algoliaDataCollector = $client->getProfile()->getCollector('algolia.client_data_collector');
$transactions = $algoliaDataCollector->getTransactions();
// Assert transactions
```

- Push mocked responses into a response stack that will be returned by the `DebugClient` if requests are disabled (`disable_requests` config):
```
// algolia.client -> DebugClient
$container->get('algolia.client')->pushResponse(['my' => 'response']);
```

**Toolbar**
screen shot 2016-11-18 at 11 15 37

**Profiler**
screen shot 2016-11-18 at 11 25 18

### CODE REVIEW

**Comment by maxiloc** [comment]
@venyii Thanks for this. We'll review that as soon as possible

**Comment by chrjean** [comment]
Interesting, any news?

**Comment by rayrutjes** [comment]
This looks great. I do think though that this kind of package should be released as a separate package. @venyii are you interested in shipping it?

If not possible with the current design of the bundle, we will need to make sure in a future release this kind of integration is possible.

I'm closing this for the time being. Let us know if you need any help releasing this @venyii .

Thanks for your support and your patience.

**Comment by venyii** [comment]
Hi @rayrutjes, to be honest, I don't think this should be a separate package. A `DataCollector` is usually included as part of a Symfony bundle for profiling/debugging purposes in the Symfony Web Debug Toolbar, not a single package.

See the official [FrameworkBundle](https://github.com/symfony/symfony/tree/master/src/Symfony/Bundle/FrameworkBundle/DataCollector), [SecurityBundle](https://github.com/symfony/symfony/tree/master/src/Symfony/Bundle/SecurityBundle/DataCollector) or 3rd-party bundles like [SncRedisBundle](https://github.com/snc/SncRedisBundle/tree/master/DataCollector) as examples.

Could you elaborate why you'd want to separate these?

Thanks!

**Comment by rayrutjes** [comment]
You want check this out @julienbourdeau ? I think we should move forward.

**Comment by jupeter** [comment]
Hi guys, agree with @venyii.
Created separated bundle for that:
https://packagist.org/packages/jupeter/datacollector-algolia-search-bundle
I will be appreciated for any comments.

**Comment by julienbourdeau** [comment]
Hi @jupeter,

I assume you meant that you agree with @rayrutjes. What did you choose to make it a separate package?

**Comment by jupeter** [comment]
Hi @julienbourdeau,
yep - agree with @rayrutjes. Sorry for mistake. 
About choose, pragmatic thing - i was requirement from my current project to implement DataCollector for Algolia and it was much easier to do it as separate bundle. 
Matter of your future decisions: 
 - if you prefer to have in this bundle DataCollector, I will remove the package in future;
 - if you want have new package in "algolia" github - please take it;

**Comment by julienbourdeau** [comment]
Personally, I like having only one package as long as it doesn't add overhead in production.

The debug extension will not work without AlgoliaBundle and its code also relies on AlgoliaBundle. If for some reasons we change the signature of `doRequest`, we will need to update 2 separates codebase:

* the Git history is a bit harder to track
* it can results in dependency issues (if you update only one of the libs)

Also, I think it's **a really cool** feature so I'd rather see activated by default 😄

**Comment by alcaeus** [comment]
@julienbourdeau any update on this one?

**Pull request merged**
