### PR TITLE
Making the AlgoliaSearch\Client service public

### PR DESCRIPTION
**Pull request by aequasi**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | yes 
| BC breaks?        | no     
| Need Doc update   | no

## Describe your change

Makes the AlgoliaSearch\Client service public, and autowireable

### CODE REVIEW

**Comment by nunomaduro** [comment]
@aequasi Thanks for this Pull Request.

By default, the `AlgoliaSearch\Client` is not public in the container, but you can easily expose it.
In the service file of your project, `config/services.yaml` in a typical Symfony 4 app,
you can alias it and make it public with the following code:

```yaml
services:
    algolia.client:
        alias: algolia_client
        public: true
```

Or in XML

```xml
<services>
    <service id="algolia.client" alias="algolia_client" public="true" />
</services>
```

### Example

Here is an example of how to use the client after your registered it publicly.

```php
class TestController extends Controller
{

    protected $indexManager;

    public function __construct(IndexManagerInterface $indexingManager)
    {
        $this->indexManager = $indexingManager;
    }

    public function testAction()
    {
        $algoliaClient = $this->get('algolia.client');
        var_dump($algoliaClient->listIndexes());

        $index = $algoliaClient->initIndex(
            $this->indexManager->getFullIndexName(Post::class)
        );

        var_dump($index->listApiKeys());

        die;
    }
}
```

**Comment by aequasi** [comment]
Yup. This is just not consistent with the recommendations from the Symfony team as service ID's should be their class name so it can be auto-wired.

I also don't really know why this class is private to begin with. It serves no purpose being private and, being the Algolia Search Bundle, one could expect to have access to the underlying client in some way, without altering configuration.

**Comment by nunomaduro** [comment]
@aequasi Thanks for your proposal. The Algolia Search Bundle is **engine agnostic**. That means that people are able to create/use new engine classes (different from Algolia) to add full-text search into they Symfony applications.

The Client class only makes sense when you are using the Algolia Engine. That's why we have written docs about how to make the client service public: https://github.com/algolia/search-bundle#using-algolia-client.

**Comment by julienbourdeau** [comment]
Yes, when I wrote the v3 I wanted to make it agnostic and making the user expose the service himself was sorf ot a warning that they can't switch the engine easily anymore.

The PR #265 will be introducing an AlgoliaIndexManager, which is one step toward "not so agnostic". Maybe we should reconsider and merge this PR 🤔  If we make it public, it should definitely be autowireable 🚀 

I doubt it brought much value to the package to be able to use it with other Engines, but I definitely think that the NullEngine and AlgoliaSyncEngine are great feature!

**Comment by alcaeus** [comment]
> Makes the AlgoliaSearch\Client service public, and autowireable

Any service can be autowired as long as the autowiring rules allow for service discovery. By default, autowiring rules mean that if you typehint `AlgoliaSearch\Client $searchClient`, it looks for a service **named** `AlgoliaSearch\Client` - if it doesn't find it, it can't autowire a service.

In Symfony 4.1, you can use the `_bind` defaults to configure a specific service for a certain name or type:
```yaml
services:
     _defaults:
         bind:
             $searchClient: '@algolia_client'
             AlgoliaSearch\Client: '@algolia_client'
```

In this case, you can use either (you don't need both) options to automatically bind the search client in your controllers. The other option is to create a service alias named `AlgoliaSearch\Client` that aliases `algoliasearch_client`. In Symfony 4.2, you can combine them and only bind the client if name **and** type match, as is described in the [blog entry](https://symfony.com/blog/new-in-symfony-4-2-autowiring-by-type-and-name) for this feature.

Either way, auto wiring does not require the service to be public. Instead, services should be private to enforce proper inversion of control and making dependencies explicit. If you really can't inject the search client, you should not inject the entire container but rather inject a service locator that just knows about the services you care about. See the [Symfony documentation](https://symfony.com/doc/current/service_container/service_subscribers_locators.html#defining-a-service-locator) for more info on service locators.

@julienbourdeau I recommend closing this PR: having the service public does not change anything about autowiring, it's all about the service name and the container configuration. Making the service public just exposes a service to the entire outside world which shouldn't be done. FWIW, the bundle can easily go ahead and provide an alias for the client to make autowiring easier; this can also be overridden by consuming apps if they want to use a different service.

**Comment by aequasi** [comment]
> Any service can be autowired as long as the autowiring rules allow for service discovery.

Any service can only be autowired by an app (not the bundle) if the service is public. 

I shouldn't have to declare oddities just to be able to access the Algolia Search client, in the Algolia search bundle...


I fully understand how to use auto-wiring, and know how to get around the private class. The point of this PR is to get rid of the work-arounds because they shouldn't be necessary.

**Comment by alcaeus** [comment]
> The point of this PR is to get rid of the work-arounds because they shouldn't be necessary.

The only "workaround" necessary is to define a service alias for the client that points to the `algolia.client` service, not more, not less. Autowiring depends on the service ID and not the discoverability of the service outside of the container. The `public` option is only used to specify whether the service can be fetched from the container using `ContainerInterface::get`.

**Comment by stof** [comment]
> Any service can only be autowired by an app (not the bundle) if the service is public.

that's not true. Declaring a service private does not mean that only the bundle declaring it can reference it. There is only one container per kernel. Service definitions are not tied to a bundle at all.

The difference between a public and private service is that a public service can be accessed at runtime through `Container::get`, while private services can only be referenced by other services (they are private to the container, not to the bundle). As autowiring happens at compile time to create such references inside the container, private services are fine.

**Comment by stof** [comment]
What should be done though is defining a private alias `AlgoliaSearch\Client` pointing to this `algolia.client` service, so that autowiring for this service works out of the box for people needing to perform the advanced things

**Comment by aequasi** [comment]
Thanks for clarifying that @stof . Misunderstanding on my part then.

**Pull request closed without merging**
