### PR TITLE
Symfony 7 support

### PR DESCRIPTION
**Pull request by flegars**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | no    
| BC breaks?        | yes     
| Related Issue     | #377
| Need Doc update   | no

## Describe your change

This is a an initial work on symfony 7 support.

### CODE REVIEW

**Comment by Bukashk0zzz** [comment]
Hi, @DevinCodes 

I think it's time :)

It's time to add Symphony 7 and ORM 3 support.

Any plans on this?

**Comment by DevinCodes** [comment]
Hey all! Sorry this has been pending for a while, I just came back from paternity leave. I'll try to test and get this out this week.

**Comment by DevinCodes** [comment]
Just a quick update on this for the sake of transparency, there's a bit more work that needs to be done to get this to work. My progress so far is on the https://github.com/algolia/search-bundle/tree/pr-380 branch, but it's not done yet. I don't have time this or next week but will get back to it once I'm back at work.

**Comment by pedrocasado** [comment]
doctrine/event-manager 2.0.1 has been released

it should be fine to add doctrine/event-manager: "^1.1 || ^2.0"

**Comment by Kaaly** [comment]
Some news on this PR ? Symfony 7 is out from some months now

**Comment by wlasnapl** [comment]
Any update?

**Comment by DevinCodes** [comment]
Sorry all, this work got de-prioritized internally so I've only had time to look at this this week. There were quite some more changes that needed to be made to get the CI to pass, so I've opened a separate PR for that: https://github.com/algolia/search-bundle/pull/381

As I'm far from a Symfony expert, I would love to have another set of eyes on this if possible, and maybe even someone that could try it out. Feel free to leave any comments on the PR I shared, I'll address the comments that come in. If all goes well, I'll release a new version with v7 support on Monday.

Apologies again for the delay on this, thank you for your patience 🙇‍♂️

**Comment by DevinCodes** [comment]
Thank you for bootstrapping the PR, I've had to open another one with all the changes to make the CI etc.. pass since there were a lot more changes to do unfortunately. I'm closing this PR in favor of https://github.com/algolia/search-bundle/pull/381.

Thank you again! 🙇‍♂️

**Pull request closed without merging**
