### PR TITLE
Added option to disable the event listeners

### PR DESCRIPTION
**Pull request by florentdestremau**
See #122 for the reason.

### CODE REVIEW

**Comment by alcaeus** [comment]
IMO, this is not a good way to solve the problem. You want to disable the indexer, not the event subscriber. #57 adds a data collector which also includes a `disable_requests` option on the client which ensures that none of your indexing requests (including those triggered manually, not only those triggered by Doctrine operations) actually hit their services.

**Comment by florentdestremau** [comment]
The data collector is a separate bundle, why would I be needing another bundle to disable this one ?

I want to manually index my entities, say with a rabbitmq command, the listeners are making a request to algolia that is falsy in my case (linked entity not updated), so I would rather take back control on the indexing

**Comment by alcaeus** [comment]
> The data collector is a separate bundle

It's not. It's a pull request for this bundle to focus on development/test environments (thus the `disable_requests` switch). I was merely bringing it up as an example on how to prevent requests to the algolia services.

**Comment by florentdestremau** [comment]
well I see @jupeter needed to create his own: https://packagist.org/packages/jupeter/datacollector-algolia-search-bundle because the PR was not merged yet, and it's been a complete year since the PR opening and yet it wasn't merged, so I wouldn't rely on it as "available"

The easiest way I found until now to stop communicating with algolia was to change the `config_test.yml` and insert a simple new config that would fail silently:

    # app/config/config_test.yml
    parameters:
        algolia.application_id: test
        algolia.api_key: test

I don't really have the time to go on a full feature to gently disable the whole bundle, so I feel like making a pragmatic way to "unplug" it from doctrine, as I don't have a `reindex` call in my tests and neither in my fixtures.

I will rename the option from `disable` to `disableDoctrineListeners` to follow the idea of @demagu in #122

**Comment by tristanbes** [comment]
@florentdestremau : When you change the application_id OR api_key, the error is currently **not** silent. It stop the execution of what you were doing.

**Comment by julienbourdeau** [comment]
Hi 👋,

I have been working a new version of the bundle and I just pushed it on the master branch.
I have taken this issue into account and the new version provide an easy way to:

- easily unsubscribe from doctrine events in configuration
- _mute_ all call to Algolia

I'd love to have your feedback about it :) You can find the doc and details in the README.md.

**Comment by tristanbes** [comment]
Can you tag a new version please ? @julienbourdeau

**Comment by julienbourdeau** [comment]
Right, I just tagged `3.0.0-BETA`. Thanks!

**Comment by tristanbes** [comment]
I can try, and give you feedback as soon as I have an upgrade guide to rely on :D

**Comment by julienbourdeau** [comment]
I'd rather close this PR since I merged #57 which allows developers to disable calls to Algolia.

Thanks a lot for you contribution, I sincerly appreciate and I'm it took so long to take action on this PR 🙏

**Pull request closed without merging**
