### PR TITLE
Fixed wrong method being called when removing an entity

### LINKED ISSUE #180: [3.0] Can't delete an entity: bundle crash the application
Hello,

The bundle (`3.0.0-BETA3` or `dev-master` ) is throwing an error when trying to remove an entity:
`Warning: urlencode() expects parameter 1 to be string, array given`

warning__urlencode___expects_parameter_1_to_be_string__array_given__500_internal_server_error_

### PR DESCRIPTION
**Pull request by tristanbes**
Fixed #180

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Nice catch! Thank you very much.

**Comment by tristanbes** [comment]
You should tag a new version since this bug makes the bundle not usable.

**Comment by tristanbes** [comment]
ping @julienbourdeau for tagging a new version.

**Comment by julienbourdeau** [comment]
I tagged the beta4. Dont hesitate to use the master branch for testing :)

**Pull request merged**
