### PR TITLE
Allow doctrine/persistence version up to 3.0

### PR DESCRIPTION
**Pull request by Kaaly**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | no
| BC breaks?        | no     
| Related Issue     | -
| Need Doc update   | no

## Describe your change

Bump doctrine/persistence major version to 3.0

### CODE REVIEW

**Review by johnhout — APPROVED** [review]

**Comment by Bukashk0zzz** [comment]
Hi, @DevinCodes maybe you have time to check this?

@Kaaly Maybe you can pull changes from master to this brunch?

There not too much changes in doctrine/persistence 
https://github.com/doctrine/persistence/blob/3.1.x/UPGRADE.md

**Review by DevinCodes — APPROVED** [review]
Looks good to me, thank you for this! I'll see if we can make a release this week to get this out.

**Comment by Bukashk0zzz** [comment]
@DevinCodes Thanks :)

**Comment by DevinCodes** [comment]
This is released now in [v6.0.1](https://github.com/algolia/search-bundle/releases/tag/6.0.1). Thank you for the contribution!

**Pull request merged**
