### PR TITLE
fix: do waitTask on all tasks before moving index

### PR DESCRIPTION
**Pull request by DevinCodes**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no    
| BC breaks?        | no     

## Describe your change
This updates the `SearchImport` command to wait until all indexing operations are done before performing a `moveIndex` operation. This could prevent accidental loss of data.

### CODE REVIEW

**Comment by DevinCodes** [comment]
@chloelbn have you seen this error in the CI before? 🤔

**Review by matthewbond — COMMENTED** [review]
The change looks great, for the CI errors, if I understand this change right: https://github.com/symfony/symfony/pull/40986 then getOption will now sometimes return null, could this be why there are these errors in the CI?

**Comment by DevinCodes** [comment]
@matthewbond You're right, fixed this in c2df2d4efb229510bb527136bd8cb27961b5eacc. 

I was referring to the following error however:
```
Fatal error: Could not check compatibility between Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Zend\Code\Generator\ClassGenerator $classGenerator): void and ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator::generate(ReflectionClass $originalClass, Laminas\Code\Generator\ClassGenerator $classGenerator), because class Zend\Code\Generator\ClassGenerator is not available in /home/circleci/project/vendor/symfony/proxy-manager-bridge/LazyProxy/PhpDumper/LazyLoadingValueHolderGenerator.php on line 33
```

[It looks like](https://github.com/symfony/symfony/issues/41742) this comes from the fact that v3.4 of Symfony is no longer supported. I've dropped support for the older version of Symfony in d618f45c6996612b3edd3def09d745c491b7981f.

**Comment by DevinCodes** [comment]
[This issue](https://github.com/symfony/symfony/issues/41742) mentions a fix: requiring the `laminas/laminas-zendframework-bridge` dependency. Added that in 3ab55be214f0114a895525f0f0544039d5cc8d00

**Comment by DevinCodes** [comment]
@matthewbond should be good now 😄

**Review by matthewbond — APPROVED** [review]
LGTM

**Pull request merged**
