### PR TITLE
[3.0] Uses the built-in serializer service

### PR DESCRIPTION
**Pull request by tristanbes**
This PR is a better alternative to #147.

To me it's a better solution because if **fixes all the drawbacks of current implementation**:

- You have to set the Normalizer attribute `public=true` when defining your custom Normalizer service.
- You have to overwrite built-in Symfony Normalizer services to expose them as public, otherwise you cannot use them.
- You have to EXPLICITLY tell all the Normalizers dependencies. If you object has for example 10 relations to other objects, you have to add those 10 Normalizers in your indice configuration

With this PR you get: 

- [x] fixes 🎉
- [x] deletion of the `SearchableArrayNormalizer` because built-in Symfony `Normalizers` are way more powerful and covers more cases out of the box. (see documentation)
- [x] simpler configuration
- [x] some cs fix
- [x] a slightly better documentation and examples

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Overall I really like it, I'm totally in favor of doing it this way.

I'm happy to get rid of the `SearchableArrayNormalizer` 🎉 . I wasn't very happy with it but it was a good enough solution at the time. `ObjectNormalizer` seems very powerful but I found it a bit under-documented.

I'm a bit concerned that by default, all relationships will get index. I believe this will results in big records (probably often to big for the Algolia 10KB size limit). I'm sort of wanted to allow devs to index everything right away, without worrying about adding annotation (like in v2) or having to write normalizers.

**Comment by tristanbes** [comment]
Well you have to compromize, 
either they do 0 config out of the box, and a few might hit the 10KB size limit,
either they write custom `Normalizer` which we should encourage them to.

TBH, there are high chances they'll hit `Normalization` common problems before they hit the size limit such as `circular reference`, that should be solved with custom `Normalizers`

**Comment by julienbourdeau** [comment]
I think with this, we could also leverage [groups](https://symfony.com/doc/current/components/serializer.html#attributes-groups). We could call the serializer with `'groups' => ['searchable'],` [here](https://github.com/algolia/search-bundle/blob/master/src/SearchableEntity.php#L36-L38). I guess you can also extract the string to `SearchFormat`.

Then you can easily mimic the v2 behavior and use annotations. What do you think?

**Comment by tristanbes** [comment]
Something like this (see commit) ? @julienbourdeau

**Comment by julienbourdeau** [comment]
Adding something on the config is also the only idea I came up with as well. Auto detecting groups sounds _too much_. I think we can go for this 👍 🎉

**Comment by tristanbes** [comment]
Should be ready, I didn't test it though, because I wrote all `normalizers` in my app

**Comment by julienbourdeau** [comment]
I fixed the last bit and I added an array "extraParam" arguments to searchableEntity instead of the useSerializerGroup.

I wish I could find a clever way to attach this information to the entity, rather than the index. Today 1  and only 1 entity goes into 1 and only one index. I hope one day we can have multiple entities into multiples indices but it makes everything a whole lot more complicated.

**Comment by tristanbes** [comment]
I think we can wait user to actually use the bundle and see if they have this needs no ? Or plan it for a 3.1

**Comment by julienbourdeau** [comment]
Yes I don't intend to do it soon, I was more sharing a dream :D

Thanks a lot for this PR, it really improved the bundle!

**Pull request merged**
